CREATE TABLE IF NOT EXISTS SUS_SUSCRIPTORES (
  id INT NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  anyo_nacimiento INT NOT NULL,
  total_suscripciones INT NOT NULL,
  PRIMARY KEY (id))
;


-- -----------------------------------------------------
-- Table `COMENTARIOS`
-- -----------------------------------------------------
CREATE SEQUENCE SUS_COMENTARIOS_seq;

CREATE TABLE IF NOT EXISTS SUS_COMENTARIOS (
  id INT NOT NULL DEFAULT NEXTVAL ('SUS_COMENTARIOS_seq'),
  comentario VARCHAR(200) NOT NULL,
  puntaje INT NOT NULL,
  fecha TIMESTAMP(0) NOT NULL,
  CLIENTES_id INT NOT NULL,
  PRIMARY KEY (id)
 ,
  CONSTRAINT fk_COMENTARIOS_CLIENTES
    FOREIGN KEY (CLIENTES_id)
    REFERENCES SUS_SUSCRIPTORES (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
 ;
